"""Static checks on the browser assets.

These exist because of a bug that shipped and stayed shipped: topology.js
called ``buildDataUrl()`` without importing it, so the map silently failed
to load in every browser for several releases. Nothing caught it — the
jsdom harness concatenates page-utils.js and the page script into one
scope, which makes a missing import resolve just fine.

A parser would be better than regexes, but this project has no JS
toolchain and these checks only need to answer three blunt questions:

- does a page use something from page-utils without importing it?
- does a page import something that no longer exists?
- do the files the HTML references actually exist?
"""

import re
from pathlib import Path

import pytest

WEB = Path(__file__).resolve().parents[3] / "app" / "web"
JS_DIR = WEB / "assets" / "js"
PAGE_UTILS = JS_DIR / "page-utils.js"

PAGE_SCRIPTS = sorted(p for p in JS_DIR.glob("*.js") if p.name != "page-utils.js")

IMPORT_RE = re.compile(r'import\s*\{([^}]*)\}\s*from\s*"\./page-utils\.js";')


def exported_names() -> set:
    return set(re.findall(r"^export const (\w+)", PAGE_UTILS.read_text(), re.M))


def imported_names(source: str) -> set:
    match = IMPORT_RE.search(source)
    if not match:
        return set()
    return {name.strip() for name in match.group(1).split(",") if name.strip()}


def locally_declared(source: str) -> set:
    """Names the file defines itself, which shadow anything importable."""
    return set(
        re.findall(r"^\s*(?:const|let|var)\s+(\w+)\s*=", source, re.M)
    ) | set(re.findall(r"^\s*function\s+(\w+)\s*\(", source, re.M))


def called_names(source: str, candidates: set) -> set:
    body = source[IMPORT_RE.search(source).end():] if IMPORT_RE.search(source) else source
    return {name for name in candidates if re.search(rf"\b{name}\s*\(", body)}


@pytest.mark.parametrize("script", PAGE_SCRIPTS, ids=lambda p: p.name)
class TestPageScripts:
    def test_uses_nothing_it_did_not_import(self, script):
        source = script.read_text()
        exports = exported_names()
        used = called_names(source, exports)
        available = imported_names(source) | locally_declared(source)
        missing = used - available
        assert not missing, (
            f"{script.name} calls {sorted(missing)} from page-utils.js without "
            f"importing it — this throws a ReferenceError in the browser"
        )

    def test_imports_nothing_that_no_longer_exists(self, script):
        stale = imported_names(script.read_text()) - exported_names()
        assert not stale, f"{script.name} imports {sorted(stale)}, which page-utils.js no longer exports"

    def test_imports_are_actually_used(self, script):
        """Unused imports are usually a rename that half-landed."""
        source = script.read_text()
        imported = imported_names(source)
        # An import may be referenced without being called (passed as a
        # callback, say), so look for the bare identifier too.
        body = source[IMPORT_RE.search(source).end():] if IMPORT_RE.search(source) else source
        unused = {name for name in imported if not re.search(rf"\b{name}\b", body)}
        assert not unused, f"{script.name} imports {sorted(unused)} without using them"


class TestPages:
    @pytest.mark.parametrize(
        "page", sorted(WEB.glob("*.html")), ids=lambda p: p.name
    )
    def test_referenced_assets_exist(self, page):
        """Every local script, stylesheet, and image the page names is present."""
        source = page.read_text()
        refs = re.findall(r'(?:src|href)="([^"]+)"', source)
        missing = []
        for ref in refs:
            if ref.startswith(("http", "#", "//", "mailto:")):
                continue
            if ref in {"app-config.js"}:  # generated by the server, not a file
                continue
            if not (WEB / ref).exists():
                missing.append(ref)
        assert not missing, f"{page.name} references missing files: {missing}"


class TestStylesheet:
    """A typo in a custom property drops the whole declaration, silently.

    ``padding: var(--space-4) var(--space-5)`` with no --space-5 defined
    does not fall back to something sensible — the browser throws the
    padding away entirely, and the only symptom is a cramped layout.
    """

    def test_every_custom_property_used_is_defined(self):
        css = (WEB / "assets" / "css" / "styles.css").read_text()
        defined = set(re.findall(r"^\s*(--[\w-]+)\s*:", css, re.M))
        # var(--x, fallback) is fine even when --x is absent; those are
        # written deliberately, so only flag the single-argument form.
        used = set(re.findall(r"var\(\s*(--[\w-]+)\s*\)", css))
        undefined = sorted(used - defined)
        assert not undefined, f"styles.css uses undefined custom properties: {undefined}"

    def test_javascript_only_sets_properties_that_exist(self):
        """JS reads theme colours by name; a rename would break them quietly."""
        css = (WEB / "assets" / "css" / "styles.css").read_text()
        defined = set(re.findall(r"^\s*(--[\w-]+)\s*:", css, re.M))
        for script in PAGE_SCRIPTS:
            used = set(re.findall(r'getPropertyValue\(\s*"(--[\w-]+)"', script.read_text()))
            undefined = sorted(used - defined)
            assert not undefined, f"{script.name} reads undefined properties: {undefined}"


class TestTopologyDefaultScope:
    """The topology opens on live connections only.

    A graph full of machines nobody at this deployment has a session to
    reads as noise — several are systems a given user has never heard of.
    But a status-page-only fleet has no live sessions at all, and must not
    open on an empty canvas, so the default is conditional.
    """

    SOURCE = (JS_DIR / "topology.js").read_text()

    def test_the_default_is_decided_from_the_data(self):
        assert "const resolveDefaultScope" in self.SOURCE
        assert "connected > 0" in self.SOURCE, (
            "the default must depend on there being something connected"
        )

    def test_an_absent_url_parameter_is_not_off(self):
        """?connected=0 is off; no parameter at all means 'decide for me'."""
        assert 'connectedParam === null ? null' in self.SOURCE
        assert 'params.set("connected", "0")' in self.SOURCE, (
            "turning it off must survive a reload"
        )

    def test_the_filter_treats_undecided_as_show_everything(self):
        assert "connectedOnly === true && !node.connected" in self.SOURCE, (
            "a null (undecided) scope must not hide anything"
        )

    def test_it_says_what_it_is_hiding(self):
        assert "holds " in self.SOURCE and "Live connections only" in self.SOURCE


class TestApiPageBaseUrl:
    """The base URL panel advertises what callers append to."""

    SOURCE = (JS_DIR / "api.js").read_text()

    def test_an_empty_path_resolves_to_the_directory(self):
        """new URL("", ".../api.html") is api.html itself, not the base."""
        assert '|| "."' in self.SOURCE, (
            'an empty relative path must become "." or the panel advertises '
            "the page's own URL"
        )


class TestFleetCardIsCalm:
    """A card says what a machine is; the table says everything else.

    The first version repeated the site (already the group heading), the
    login node, and a provenance line on every card, which is a table with
    worse density.
    """

    SOURCE = (JS_DIR / "app.js").read_text()

    def test_the_card_does_not_repeat_the_table(self):
        card = self.SOURCE[self.SOURCE.index("function systemCard(") :]
        card = card[: card.index("function systemCardLinks(")]
        assert "row.login" not in card, "the login node belongs in the detail view"
        assert "system-card-facts" not in card, "one meta line, not a definition list"
        assert "system-card-source" not in card, "provenance moved to the tooltip"

    def test_it_still_says_what_the_machine_is_for(self):
        card = self.SOURCE[self.SOURCE.index("function systemCard(") :]
        card = card[: card.index("function systemCardLinks(")]
        assert "row.description" in card

    def test_a_long_description_cannot_stretch_the_row(self):
        css = (WEB / "assets" / "css" / "styles.css").read_text()
        block = css[css.index(".system-card-desc {") :]
        block = block[: block.index("}")]
        assert "-webkit-line-clamp: 2" in block


class TestStaleCacheResilience:
    """A browser holding the previous index.html must still see systems.

    The cards container arrived with the fleet rewrite. A cached copy of
    the older page has no such element, and the view switch would have
    hidden the table on its behalf — leaving a page with nothing in it,
    which reads as "the dashboard is down" rather than "reload me".
    """

    SOURCE = (JS_DIR / "app.js").read_text()

    def test_the_view_falls_back_to_the_table(self):
        assert 'const view = cardsHost ? currentView() : "table"' in self.SOURCE

    def test_the_table_is_never_hidden_without_a_replacement(self):
        assert "cardsHost ? view !== \"table\" : false" in self.SOURCE, (
            "with no cards container the table must stay visible"
        )


class TestFavicon:
    """Something outside the page has to be able to find the icon.

    initBrand() sets one from JavaScript, which covers a rendered tab and
    nothing else: /favicon.ico — what a session tile, a link preview or a
    browser before any script runs asks for — returned 404. The brand
    mark it pointed at is also 1109px square and up to 1.1 MB, to be drawn
    at sixteen.
    """

    def test_every_page_links_an_icon_without_javascript(self):
        for page in sorted(WEB.glob("*.html")):
            source = page.read_text()
            assert 'rel="icon"' in source, f"{page.name} has no icon link"

    def test_the_linked_icons_exist(self):
        for page in sorted(WEB.glob("*.html")):
            for href in re.findall(r'rel="(?:apple-touch-)?icon"[^>]*href="([^"]+)"', page.read_text()):
                assert (WEB / href).is_file(), f"{page.name} links a missing {href}"

    @pytest.mark.parametrize("platform", ["hpcmp", "generic"])
    def test_a_small_icon_ships_for_each_platform(self, platform):
        icon = WEB / "assets" / "img" / f"favicon-{platform}.png"
        assert icon.is_file()
        assert icon.stat().st_size < 100_000, (
            "a tab icon should not weigh more than the page"
        )

    def test_the_script_upgrades_to_the_platform_icon(self):
        source = (JS_DIR / "page-utils.js").read_text()
        assert "favicon-${platform}.png" in source
        assert "brand-${platform}.png" not in source, (
            "the 1109px brand mark is not a favicon"
        )


class TestSchedulerWording:
    """Silence from a scheduler is not the absence of one."""

    SOURCE = (JS_DIR / "quota.js").read_text()

    def test_the_card_distinguishes_idle_from_absent(self):
        assert "schedulerStatus" in self.SOURCE
        assert "no partitions online" in self.SOURCE
        assert "No scheduler detected" in self.SOURCE, "still right when true"

    def test_it_reads_the_probed_metadata(self):
        assert "metadata.has_scheduler" in self.SOURCE
        assert "metadata.scheduler" in self.SOURCE

    def test_the_explanation_is_in_the_tooltip(self):
        assert "scale to zero" in self.SOURCE


class TestSweepProgress:
    """"collecting 16/19" looked stuck, and was not.

    Polled from the node, a sweep climbs 0 -> 2 -> 6 -> 11 -> 14 -> 19 and
    finishes in about a hundred seconds. The page polled every 45s, so a
    user saw two still frames of it and read that as a hang. A bar makes
    the movement visible, and the poll speeds up while one is running.
    """

    SOURCE = (JS_DIR / "app.js").read_text()

    def test_the_poll_is_quicker_while_sweeping(self):
        assert "SWEEPING_POLL_MS" in self.SOURCE and "IDLE_POLL_MS" in self.SOURCE
        assert "scheduleNextPoll" in self.SOURCE

    def test_returning_to_the_tab_refreshes_at_once(self):
        assert "visibilitychange" in self.SOURCE

    def test_the_bar_is_only_shown_while_collecting(self):
        assert "renderSweep" in self.SOURCE
        block = self.SOURCE[self.SOURCE.index("function renderSweep") :]
        block = block[: block.index("\n}")]
        assert "if (!collecting)" in block and "hidden = true" in block

    def test_it_names_the_cluster_in_flight(self):
        """A slow cluster should be identifiable, not look like a hang."""
        assert "progress.current_cluster" in self.SOURCE

    def test_the_markup_exists_for_it(self):
        page = (WEB / "index.html").read_text()
        for element in ("sweep-progress", "sweep-fill", "sweep-note"):
            assert f'id="{element}"' in page

    def test_the_shimmer_respects_reduced_motion(self):
        """The bar animates; the global reduce block must still cover it."""
        css = (WEB / "assets" / "css" / "styles.css").read_text()
        assert "sweep-shimmer" in css
        reduce = css[css.index("@media (prefers-reduced-motion: reduce)") :]
        assert "animation-duration: 0.01ms !important" in reduce


class TestQuotaCardLinks:
    """A quota card should reach that cluster's other pages.

    The page is one long column, so seeing a system's queues meant
    scrolling back to the nav, opening Queue health, and picking the
    cluster again — which both pages already support by slug.
    """

    SOURCE = (JS_DIR / "quota.js").read_text()

    def test_every_card_variant_carries_the_links(self):
        assert self.SOURCE.count("${clusterLinks(metadata)}") == 3, (
            "GPU, compute and generic cards each need them"
        )

    def test_the_links_deep_link_by_slug(self):
        assert "queues.html?cluster=" in self.SOURCE
        assert "storage.html?cluster=" in self.SOURCE

    def test_both_targets_honour_the_parameter(self):
        """A link is only useful if the page it opens acts on it.

        queues.js selects the cluster; storage.js renders every cluster at
        once and used to ignore ?cluster= entirely, so the link landed at
        the top of the page and left you scrolling — the very thing it was
        meant to save.
        """
        queues = (JS_DIR / "queues.js").read_text()
        assert '.get("cluster")' in queues
        storage = (JS_DIR / "storage.js").read_text()
        assert '.get("cluster")' in storage
        assert "scrollIntoView" in storage

    def test_they_are_hidden_when_cluster_pages_are_off(self):
        assert "if (!clusterPagesEnabled()) return \"\";" in self.SOURCE

    def test_a_picker_jumps_between_cards(self):
        """The same control queue health has, doing what this page needed."""
        assert "renderClusterPicker" in self.SOURCE
        assert "cluster-picker-btn" in self.SOURCE, "reuse the existing control"
        assert "data-jump" in self.SOURCE

    def test_every_card_variant_is_addressable(self):
        """A jump needs somewhere to land."""
        assert self.SOURCE.count('id="cluster-${clusterSlug(metadata)}"') == 3

    def test_one_cluster_gets_no_picker(self):
        """A single card is not a list to navigate."""
        assert "ordered.length < 2" in self.SOURCE

    def test_scrolling_is_optional(self):
        """A missing scrollIntoView must not abort the rest of the handler.

        jsdom has none, and the throw skipped the aria-current update that
        followed it — a real browser would have been fine, but the guard
        costs one character and makes the behaviour testable.
        """
        for name in ("quota.js", "storage.js"):
            source = (JS_DIR / name).read_text()
            assert "scrollIntoView?." in source, name

    def test_the_name_is_escaped(self):
        """A cluster name reaches an attribute, so it must be escaped."""
        assert "const escapeHtml" in self.SOURCE, (
            "quota.js had no escapeHtml; calling one that does not exist "
            "throws at render and blanks the page"
        )


class TestBundledData:
    def test_basemap_is_present_and_shaped_correctly(self):
        """The topology map needs this file; losing it fails silently."""
        import json

        basemap = WEB / "assets" / "data" / "us-states.json"
        assert basemap.exists(), "the topology map outline is missing"
        data = json.loads(basemap.read_text())
        assert data["states"], "no state boundaries in the outline"
        assert data["country"], "no national outline (the coastline stroke)"
        for state in data["states"]:
            assert state["n"] and state["r"], f"malformed entry: {state}"
        # Small enough to bundle, which is the whole point of bundling it.
        assert basemap.stat().st_size < 200_000
