################################################################################
# start-template.sh — placeholder endpoint for the Spack MPI stack builder.
#
# This workflow builds a stack and exits; it has no service to offer. The
# endpoint exists so the workflow can be tested by the shared end-to-end test
# runner, whose pass criteria are "the run completed AND an endpoint named
# <service>-<run-slug> answers HTTP". See README.md ("The placeholder
# endpoint") -- it is expected to be removed once the runner can express a
# workflow that serves nothing.
#
# Runs on the login node after the build, through script_submitter.
#
# Consumes (from the sourced inputs.sh):
#   pw_endpoints_args        --name <service>-<run-slug>
#   service_install_prefix   Spack root, for the summary page
#   fabric_env               the resolved profile, for the summary page
#   env_dir                  the concretized environment
#   modulepath_env           the MODULEPATH build.sh resolved, one line
################################################################################

set -o pipefail

endpoint_name="$(printf '%s' "${pw_endpoints_args}" | sed -n 's/.*--name[ =]\{1,\}\([^ ]*\).*/\1/p')"
doc_root="${PWD}/endpoint-root"

# Written before anything can start, so a cancel at any moment finds it. The
# endpoint is deleted explicitly rather than left to the process kill: deleting
# it is what removes it from `pw endpoints list`, and a stale entry there
# outlives the run and is what a later run or test would trip over.
cat > cancel.sh <<EOF
#!/bin/bash
echo "[cancel] deleting endpoint ${endpoint_name}"
command -v pw >/dev/null 2>&1 || export PATH="\${PATH}:\${HOME}/pw"
pw endpoints delete "${endpoint_name}" 2>/dev/null || true
pkill -u "\$(id -u)" -f "http.server .*${doc_root}" 2>/dev/null || true
exit 0
EOF
chmod +x cancel.sh

# A static page, served from its own directory: the run directory holds
# inputs.sh and the full build log, and none of that should be reachable by URL.
mkdir -p "${doc_root}"
{
  echo "<!doctype html><meta charset=utf-8><title>spack-builder</title>"
  echo "<h1>Spack stack built</h1>"
  echo "<p>Run <code>${PW_RUN_SLUG:-?}</code> on <code>$(hostname)</code>, $(date -u +%FT%TZ).</p>"
  echo "<pre>"
  [ -f "${fabric_env:-}" ] && sed 's/&/\&amp;/g; s/</\&lt;/g' "${fabric_env}"
  echo "</pre>"
  echo "<p>Spack root: <code>${service_install_prefix:-?}</code></p>"
  # Written by build.sh, which is the only place that knows both module trees:
  # the stack's (keyed by the RESOLVED target, not this node's `spack arch`) and
  # the generic-target one holding the external compiler. Absent when the build
  # stopped before the module refresh -- concretize_only, most often.
  if [ -s "${modulepath_env:-}" ]; then
    modulepath="$(sed 's/&/\&amp;/g; s/</\&lt;/g' "${modulepath_env}")"
    echo "<p>Modules:</p><pre>export MODULEPATH=${modulepath}:\$MODULEPATH"
    echo "module load gcc          # gcc/g++/gfortran, to compile"
    echo "module load openmpi      # or mpich / intel-oneapi-mpi"
    echo "module load gromacs</pre>"
    echo "<p>MODULEPATH must name those directories, not their parent: the"
    echo "autoload lines inside the modulefiles are bare names resolved against"
    echo "a MODULEPATH entry.</p>"
  else
    echo "<p>No module tree was generated by this run.</p>"
  fi
  echo "<p>This endpoint is a placeholder: it exists only so the end-to-end test"
  echo "runner has an endpoint to check. Nothing here is required by the build.</p>"
} > "${doc_root}/index.html"

echo "::group::Start Service"
echo "::notice::Serving the placeholder endpoint: pw endpoints run ${pw_endpoints_args} -- python3 -m http.server {port} --bind 0.0.0.0 --directory ${doc_root}"

set -x
# {port} is replaced by pw endpoints run with the local port it forwards to.
pw endpoints run ${pw_endpoints_args} -- \
    python3 -m http.server '{port}' --bind 0.0.0.0 --directory "${doc_root}"
rc=$?
set +x

if [ ${rc} -ne 0 ]; then
    # `pw endpoints run` blocks for the life of the service, so it also returns
    # non-zero when wait_for_endpoint cancels this job after a SUCCESSFUL
    # launch -- which is exactly how the run is released. Only a launch that
    # never registered is a real failure. (Same reasoning as webshell's start
    # template; that line once cancelled whole runs whose service was up.)
    if [ -n "${endpoint_name}" ] && pw endpoints list 2>/dev/null | awk '{print $1}' | grep -qxF "${endpoint_name}"; then
        echo "::notice::Endpoint ${endpoint_name} served until this job was cancelled; exiting cleanly"
        exit 0
    fi
    echo "::error title=Error::pw endpoints run failed and ${endpoint_name:-<unnamed>} never registered"
    exit 1
fi
echo "::endgroup::"
