#!/usr/bin/env python3
"""Generate schemas/openapi.yaml from the endpoint catalog.

The hand-written spec drifted: it documented two endpoints that were never
implemented and missed five that were. Generating it means the only way to
change the spec is to change the catalog, which a test already pins to the
router.

The generated document is deliberately lean on response schemas. A correct
list of endpoints with described parameters is worth more than detailed
response bodies that go stale silently; callers get the real shape from a
live request or from the API page.

Usage:
    python scripts/build_openapi.py          # rewrite schemas/openapi.yaml
    python scripts/build_openapi.py --check  # exit 1 if it is out of date
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[2] / "app"))

from src.server.api_catalog import ENDPOINTS, groups  # noqa: E402

SPEC_PATH = Path(__file__).resolve().parents[1] / "schemas" / "openapi.yaml"

HEADER = (
    "# Generated by scripts/build_openapi.py from src/server/api_catalog.py.\n"
    "# Do not edit by hand — edit the catalog and regenerate.\n"
)

GROUP_DESCRIPTIONS = {
    "Fleet": "Fleet-wide status, topology and history",
    "Clusters": "Per-cluster queues, allocations and storage",
    "Decisions": "Placement rankings and generated insights",
    "Reference": "Configuration and self-description",
    "Control": "Operations that change server state",
}


def operation_id(entry: dict) -> str:
    """A stable camel-ish id derived from the path."""
    parts = [
        part.strip("{}")
        for part in entry["path"].strip("/").replace(".", "-").split("/")
        if part
    ]
    head, *rest = parts
    return head + "".join(word.title().replace("-", "") for word in rest)


def parameters(entry: dict) -> list:
    params = []
    for segment in entry["path"].split("/"):
        if segment.startswith("{") and segment.endswith("}"):
            name = segment[1:-1]
            params.append(
                {
                    "name": name,
                    "in": "path",
                    "required": True,
                    "description": f"Slug identifying the {name}",
                    "schema": {"type": "string"},
                }
            )
    for param in entry.get("params", []):
        schema = {"type": param["type"]}
        if "default" in param:
            schema["default"] = param["default"]
        params.append(
            {
                "name": param["name"],
                "in": "query",
                "required": False,
                "description": param["description"],
                "schema": schema,
            }
        )
    return params


def response(entry: dict) -> dict:
    content_type = entry.get("content_type", "application/json")
    schema: dict = {"type": "object"}
    if entry.get("returns"):
        schema = {
            "type": "object",
            "properties": {key: {} for key in entry["returns"]},
        }
    if entry.get("shape") == "array":
        schema = {"type": "array", "items": schema}
    if content_type != "application/json":
        schema = {"type": "string"}
    return {
        "200": {
            "description": entry["summary"],
            "content": {content_type: {"schema": schema}},
        }
    }


def build() -> dict:
    paths: dict = {}
    for entry in ENDPOINTS:
        description = entry["description"]
        if entry.get("notes"):
            description = f"{description}\n\n{entry['notes']}"
        operation = {
            "tags": [entry["group"]],
            "summary": entry["summary"],
            "description": description,
            "operationId": operation_id(entry),
            "responses": response(entry),
        }
        params = parameters(entry)
        if params:
            operation["parameters"] = params
        paths.setdefault(entry["path"], {})[entry["method"].lower()] = operation

    return {
        "openapi": "3.1.0",
        "info": {
            "title": "HPC Status Monitor API",
            "description": (
                "Read-only JSON over plain HTTP, no authentication, CORS open "
                "to any origin. Every panel in the dashboard is backed by one "
                "of these endpoints.\n\nThe same catalog is served live at "
                "/api/endpoints and rendered at /api.html.\n\n"
                "See docs/glossary.md for terminology."
            ),
            "version": "2.1.0",
            "license": {"name": "MIT"},
        },
        "servers": [
            {"url": "http://localhost:8080", "description": "Local development server"},
            {
                "url": "{protocol}://{host}:{port}{prefix}",
                "description": "Configurable deployment",
                "variables": {
                    "protocol": {"default": "http", "enum": ["http", "https"]},
                    "host": {"default": "localhost"},
                    "port": {"default": "8080"},
                    "prefix": {
                        "default": "",
                        "description": "URL prefix for reverse-proxy deployments",
                    },
                },
            },
        ],
        "tags": [
            {"name": name, "description": GROUP_DESCRIPTIONS.get(name, name)}
            for name in groups()
        ],
        "paths": paths,
    }


def render() -> str:
    return HEADER + yaml.safe_dump(build(), sort_keys=False, width=88, allow_unicode=True)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="verify the committed spec is current"
    )
    args = parser.parse_args()

    rendered = render()
    if args.check:
        current = SPEC_PATH.read_text() if SPEC_PATH.exists() else ""
        if current != rendered:
            print(
                "schemas/openapi.yaml is out of date — run "
                "`python scripts/build_openapi.py`",
                file=sys.stderr,
            )
            return 1
        print("schemas/openapi.yaml is current")
        return 0

    SPEC_PATH.write_text(rendered)
    print(f"wrote {SPEC_PATH} ({len(ENDPOINTS)} endpoints)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
